export const vocabularioB1 = [
  "abrazo", "acampar", "acusar", "admirar", "ahorrar", "albergue", "almacén", "almohada", "alojamiento",
  "amenaza", "amistad", "amueblar", "anuncio", "ánimo", "ansiedad", "aplicación", "aprobar", "archivo",
  "artículo", "asesinato", "aspiradora", "ataque", "atención", "aterrizaje", "atmósfera", "aventura",
  "avería", "barrer", "batería", "blog", "bombilla", "calefacción", "calidad", "canal", "cancelar",
  "cantidad", "carácter", "cárcel", "cargador", "cariño", "carrera", "castigo", "celoso", "cesta",
  "chat", "chimenea", "cirujano", "clima", "cobertura", "cobarde", "cobrar", "colchón", "comercio",
  "confiar", "conexión", "consumidor", "consumo", "contaminación", "contratar", "contrato", "cortina",
  "crédito", "crucero", "culpable", "curar", "currículum", "defensa", "delito", "denuncia", "dependiente",
  "desastre", "descargar", "desempleo", "desorden", "despedir", "despegue", "devolución", "dieta",
  "digital", "disculpa", "disparo", "divorcio", "dueño", "ecológico", "educado", "egoísta", "electricidad",
  "embarcar", "enchufe", "energía", "enlace", "entender", "entrenar", "entrevista", "envidia", "equilibrado",
  "escaparate", "especie", "etiqueta", "experiencia", "extranjero", "fregar", "frontera", "garantía",
  "gastronomía", "generoso", "grifo", "gripe", "grosero", "herida", "hogar", "honesto", "huelga",
  "humor", "ilegal", "impresora", "imprimir", "incendio", "inocente", "inquilino", "instalar",
  "interruptor", "inundación", "investigar", "jubilación", "juez", "juicio", "lesión", "ley", "lujo",
  "marca", "mareado", "martillo", "medicina", "mental", "meta", "modelo", "monedero", "monumento",
  "mudanza", "mueble", "multa", "negocio", "nota", "oferta", "operación", "paciencia", "pago",
  "paisaje", "pastilla", "perfil", "periodista", "personalidad", "planeta", "portátil", "práctica",
  "prensa", "prisión", "producto", "proteger", "publicidad", "rebajas", "recepción", "recibo",
  "reciclaje", "reclamar", "red", "reforma", "relación", "reparar", "reportaje", "residuo", "retraso",
  "reunión", "sábana", "salario", "sano", "sensible", "sentimiento", "sequía", "sincero", "sindicato",
  "síntoma", "solar", "soportar", "sospechoso", "sueldo", "suspender", "teclado", "tejado", "testigo",
  "típico", "título", "tratamiento", "usuario", "venta", "vía", "víctima", "violencia", "virus",
  "aburrimiento", "absurdo", "alegría", "apertura", "apartamento", "apto", "asco", "asqueroso",
  "ayuda", "biodegradable", "blando", "camping", "cerámica", "chiste", "círculo", "colgar",
  "colorido", "compartir", "compra", "cuadrado", "curso", "delicado", "electrónico", "enfado",
  "escala", "estupendo", "ético", "extravagante", "fomentar", "fomento", "frágil", "horror",
  "horroroso", "ilusión", "ilógico", "imagen", "impuesto", "informar", "innecesario", "insuficiente",
  "institucional", "intolerable", "justo", "llamada", "llamativo", "locura", "lógico", "lujoso",
  "municipal", "nerviosismo", "objetivos", "opinión", "orgánico", "ovalado", "pena", "pereza",
  "personajes", "policíaca", "poliéster", "práctico", "proximidad", "rabia", "reciclable", "reciclado",
  "rectangular", "reutilizable", "reutilización", "reutilizar", "reversible", "rombo", "rugoso",
  "sanidad", "sencillo", "sólido", "sorprendente", "sorpresa", "suficiente", "terrible", "texto",
  "tontería", "triangular", "tristeza", "uso", "valla", "vegano", "vergüenza", "padecer", "sufrir",
  "recetar", "desmayarse", "enfermar", "sanar", "contagiar", "recuperarse", "empeorar", "mejorar",
  "toser", "estornudar", "diagnosticar", "ingresar", "cicatrizar", "aliviar", "prevenir", "temblar",
  "transpirar", "inflamarse", "colesterol", "infarto", "parálisis", "alergia", "mareo", "alérgico",
  "nocivo", "benigno", "maligno", "saludable", "invidente", "funcionario", "atasco", "cojín",
  "fila", "vecino", "alquiler", "recibo", "propina", "rutina", "hipoteca", "avería", "presupuesto",
  "entorno", "peatón", "acera", "comisaría", "trámite", "despensa", "chupar", "tragar", "mamar",
  "atar", "discutir", "quejarse", "protestar", "compartir", "convivir", "madrugar", "trasnochar",
  "alquilar", "reformar", "gestionar", "solucionar", "reservar", "pertenecer", "potable", "sobrio",
  "borracho", "puntual", "informal", "asequible", "hospitalario", "doméstico", "ajeno", "urbano",
  "rural", "cotidiano", "arquitecto", "barroco", "fresco", "muralismo", "diseño", "estilo",
  "movimiento", "obra", "retrato", "escultura", "pintura", "lienzo", "galería", "patrimonio",
  "escenario", "guion", "ensayo", "reseña", "estreno", "boceto", "subasta", "espectador",
  "protagonista", "editorial", "partitura", "rodaje", "melodía", "diseñar", "representar", "exponer",
  "interpretar", "inspirar", "ilustrar", "rodar", "ensayar", "publicar", "aplaudir", "componer",
  "esculpir", "entretener", "destacar", "artístico", "clásico", "moderno", "abstracto", "realista",
  "simbólico", "creativo", "estético", "cultural", "literario", "contemporáneo", "anónimo", "genial"
];
