export const vocabularioA2 = [
  "abierto", "abrigo", "aburrido", "aceite", "aceituna", "aceptar", "aduana", "aeropuerto", "agencia",
  "agradable", "ajo", "alegre", "algodón", "amable", "ancho", "anillo", "antes", "antipático",
  "añadir", "ascensor", "asiento", "atún", "ayudar", "azúcar", "bajar", "barato", "barba",
  "barco", "bebida", "bigote", "billete", "blusa", "bocadillo", "bolso", "botella", "brazo",
  "caja", "cajero", "calcetines", "caldo", "caliente", "cambiar", "cantar", "cara", "casado",
  "castaño", "cebolla", "centro", "cerrar", "champiñón", "champú", "chico", "chocolate", "chorizo",
  "chuleta", "cinturón", "cita", "cliente", "cocinar", "codo", "coger", "cómodo", "conocer",
  "corazón", "corbata", "crema", "creer", "cruzar", "cuello", "cuerpo", "deber", "débil",
  "decidir", "dedo", "dejar", "delgado", "delicioso", "dentista", "descansar", "describir", "desear",
  "destino", "detrás", "diente", "diferente", "difícil", "dirección", "divertido", "doctor", "doler",
  "dolor", "duro", "edad", "elegante", "elegir", "elemento", "elevar", "eliminar", "embajada",
  "embarazo", "emergencia", "emigrante", "emisión", "emitir", "emoción", "emocionante", "empezar",
  "empleado", "emplear", "empleo", "emprender", "empresa", "empresario", "enamorar", "encantar",
  "encargar", "encargo", "encender", "encima", "encontrar", "encuentro", "encuesta", "enemigo",
  "energía", "enero", "enfadar", "enfermedad", "enfermo", "engañar", "enorme", "enriquecer",
  "ensayo", "enseñanza", "enseñar", "entender", "enterar", "entonces", "entrada", "entrar",
  "entrega", "entregar", "entrenar", "entretenimiento", "entrevista", "entusiasmo", "enviar", "envidia",
  "época", "equipaje", "equipo", "error", "escalera", "escapar", "escaparate", "escape", "escena",
  "escenario", "esclavo", "escoger", "esconder", "escribir", "escritor", "escritorio", "escuchar",
  "escuela", "esencia", "esencial", "esfuerzo", "espacio", "espada", "espalda", "especial",
  "especialista", "especie", "específico", "espectacular", "espectáculo", "espejo", "esperanza",
  "esperar", "espíritu", "esposa", "esposo", "esquina", "establecer", "estación", "estacionar",
  "estado", "estadounidense", "estar", "estatua", "estilo", "estimar", "estirar", "estómago",
  "estrecho", "estrella", "estrenar", "estrés", "estructura", "estudiante", "estudiar", "estudio",
  "estupendo", "etiqueta", "experiencia", "extranjero", "fregar", "frontera", "garantía", "gastronomía",
  "generoso", "grifo", "gripe", "grosero", "herida", "hogar", "honesto", "huelga", "humor",
  "ilegal", "impresora", "imprimir", "incendio", "inocente", "inquilino", "instalar", "interruptor",
  "inundación", "investigar", "jubilación", "juez", "juicio", "lesión", "ley", "lujo", "marca",
  "mareado", "martillo", "medicina", "mental", "meta", "modelo", "monedero", "monumento", "mudanza",
  "mueble", "multa", "negocio", "nota", "oferta", "operación", "paciencia", "pago", "paisaje",
  "pastilla", "perfil", "periodista", "personalidad", "planeta", "portátil", "práctica", "prensa",
  "prisión", "producto", "proteger", "publicidad", "rebajas", "recepción", "recibo", "reciclaje",
  "reclamar", "red", "reforma", "relación", "reparar", "reportaje", "residuo", "retraso", "reunión",
  "sábana", "salario", "sano", "sensible", "sentimiento", "sequía", "sincero", "sindicato", "síntoma",
  "solar", "soportar", "sospechoso", "sueldo", "suspender", "teclado", "tejado", "testigo", "típico",
  "título", "tratamiento", "usuario", "venta", "vía", "víctima", "violencia", "virus", "vomitar",
  "acción", "anécdota", "animación", "aparición", "argumento", "aumento", "baja", "bélico",
  "biográfico", "calentamiento", "cáncer", "candidato", "coordinar", "comedia", "construcción",
  "contar", "creación", "crecimiento", "cuento", "departamento", "desaparición", "destrucción",
  "diabetes", "director", "doctorado", "documental", "drama", "envejecimiento", "episodio",
  "esperanza", "extinción", "extinguir", "ficción", "filial", "frenar", "género", "grado",
  "infantil", "invención", "inventar", "jornada", "leyenda", "mando", "máster", "maternidad",
  "narrar", "paternidad", "personal", "plantilla", "población", "precario", "prevenir", "protagonista",
  "puesto", "reducir", "relato", "romántico", "saga", "sector", "sede", "solicitar", "suspense",
  "temporal", "terror", "abandono", "activismo", "actuación", "alzhéimer", "animación", "aparición",
  "argumento", "atrevido", "aumentar", "autostop", "banner", "belleza", "bélico", "bienestar",
  "biográfico", "calentamiento", "campaña", "candidato", "cartel", "cierre", "cobertura", "colgar",
  "comedia", "comentar", "completo", "concienciar", "construcción", "consumidor", "convencer",
  "coordinar", "corrupción", "creación", "creativo", "crecimiento", "crucero", "cuento", "defensa",
  "defender", "demanda", "desaparición", "descanso", "desigualdad", "destrucción", "diabetes",
  "digno", "dirigir", "discriminación", "disminuir", "diversidad", "divertido", "divorcio",
  "doctorado", "documental", "drama", "efectivo", "emocionar", "emotivo", "encuesta", "enológico",
  "envejecimiento", "episodio", "escala", "eslogan", "esperanza", "estreno", "exigir", "éxito",
  "extinción", "extinguir", "facturar", "fantástico", "ficción", "filial", "folleto", "frenar",
  "género", "grado", "guion", "igualdad", "impactante", "impactar", "indefinido", "independencia",
  "infantil", "influencer", "injusto", "innovación", "invención", "inventar", "jornada", "juventud",
  "leyenda", "libertad", "luchar", "mando", "maternidad", "máster", "meme", "narrar", "normativa",
  "ocupación", "parcial", "paro", "paternidad", "pausa", "permiso", "personal", "persuadir",
  "placer", "plantilla", "población", "polémico", "postal", "precario", "presentación", "prevenir",
  "promocionar", "protagonista", "protestar", "provocador", "publicar", "publicista", "puesto",
  "puntual", "reducir", "reducción", "refugio", "reivindicar", "relato", "remunerado", "reserva",
  "rural", "safari", "saga", "sector", "sede", "seducir", "seguro", "sexista", "solidaridad",
  "solidario", "subida", "superhéroe", "suspense", "temporal", "terror", "trasladar", "traslado",
  "urbano", "visado"
];
